main/urls.py
from django.conf.urls import url
from main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index),

    url(r'panel/$', views.panel, name='panel'),
    url(r'panel/chats/$', views.chats, name='chats'),
    url(r'panel/chat/(?P<id>.+)/$', views.chat, name='chat'),
    url(r'panel/profile/$', views.profile, name='profile'),
    url(r'panel/servers/$', views.servers, name='servers'),
    url(r'panel/serversforsale/$', views.servers_for_sale, name='servers_for_sale'),


    #user settings
    url(r'panel/profile/img', views.load_user_img, name='load_user_img'),
    #url(r'panel/messages/$', views.panel_write_message, name='write_message'),

    url(r'panel/buyserver/(?P<id>.+)/$', views.buy_server, name='buy_server'),
    url(r'login/$', views.log_in, name='login'),
    url(r'registration/$', views.register, name='reg'),
    url(r'logout/$', views.log_out, name='logout'),
    url(r'activate/(?P<username>.+)/(?P<code>.+$)', views.activate, name='activate'),
    url(r'recovery/$', views.recovery, name='pass_recovery'),
    url(r'recovery/(?P<username>.+)/(?P<code>.+$)', views.change_pass, name='change_pass'),

    url(r'check-data/$', views.check),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monitorhost/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import main

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls'))
]

main/models.py
from django.db import models
from django.forms import ModelForm
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)




class MyUserManager(BaseUserManager):
    #use_in_migrations = True

    def create_user(self, username, first_name, last_name, email, password=None):
        """
        Creates and saves a User
        """
        if not username:
            raise ValueError('Users must have an username')
        if not first_name:
            raise ValueError('Users must have a first name')
        if not last_name:
            raise ValueError('Users must have a last name')
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, first_name, last_name, email, password):
        """
        Creates and saves a superuser
        """
        user = self.create_user(username, first_name, last_name, email,
            password=password,
        )
        user.is_admin = True
        user.is_active = True
        user.save(using=self._db)
        return user




class User(AbstractBaseUser):
    objects = MyUserManager()

    username = models.CharField(verbose_name='username', max_length=20, unique=True)
    first_name = models.CharField(verbose_name='first name', max_length=25)
    last_name = models.CharField(verbose_name='last name', max_length=25)
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True
    )
    date_joined = models.DateTimeField(verbose_name='date joined', default=timezone.now)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    money = models.FloatField(verbose_name='money of user', default=0)
    activation_code = models.CharField(max_length=20, default=objects.make_random_password(length=20))
    password_recovery_code = models.CharField(max_length=20, default='None')
    show_tips = models.BooleanField(default=True)
    photo = models.ImageField(upload_to='main/media/profile_photo/',
                              default='main/media/profile_photo/default.png')

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']

    def send_message(self, author, text, admin=False):
        Message.objects.create(recioient=self, author=author, text=text, from_admin=admin)

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def __str__(self):              # __unicode__ on Python 2
        return '%s : %s %s : %s' % (self.username, self.first_name, self.last_name, self.email)

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    def send_email(self, subject, message):
        send_mail(subject, message, settings.EMAIL_HOST_USER, [self.email], fail_silently=False)

    def send_hemail(self, subject, html):
        htmly = get_template(html)
        context = { 'user_name' : self.username, 'full_name' : self.get_full_name() , 'activation_code' : self.activation_code}
        html_content = htmly.render(context)
        msg = EmailMultiAlternatives(subject, '', settings.EMAIL_HOST_USER, [self.email])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

    def password_recovery(self):
        self.password_recovery_code = MyUserManager.make_random_password(self, length=20)
        self.save()
        htmly = get_template('email/pass_recovery_email.html')
        context = {'username': self.username, 'full_name': self.get_full_name(),
                   'pass_code': self.password_recovery_code}
        html_content = htmly.render(context)
        msg = EmailMultiAlternatives('Запрос на восстановление пароля', '', settings.EMAIL_HOST_USER, [self.email])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

class Chat(models.Model):
    users = models.ManyToManyField(User)

    def __str__(self):
        if self.users.count() == 0:
            return 'Null'
        else:
            return '%s %s' % (self.users.all()[0].username ,self.users.all()[1].username)


class Message(models.Model):
    chat = models.ForeignKey(Chat)
    date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User)
    text = models.TextField()

    def __str__(self):
        return 'From: ' + self.author.username


class Server_template(models.Model):
    price = models.IntegerField()
    name = models.CharField(max_length=60)
    processor = models.CharField(max_length=60)
    ram = models.CharField(max_length=60)
    disk = models.CharField(max_length=60)

    def __str__(self):
        return self.name

class Server(models.Model):
    owner = models.ForeignKey(User)
    ip = models.CharField(max_length=40)
    #port = models.IntegerField()
    password = models.CharField(max_length=40)
    login = models.CharField(max_length=40)
    activation_date = models.DateTimeField(null=True)
    status = models.CharField(max_length=30, default="Обрабатывается")
    price = models.IntegerField()
    name = models.CharField(max_length=60)
    # harware
    processor = models.CharField(max_length=60)
    ram = models.CharField(max_length=60)
    disk = models.CharField(max_length=60)

    def __str__(self):
        return self.name

templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'change_pass' username=username code=code %}" method="post">
    {% csrf_token %}
    <input type="password">
    <input type="password" name="password">
    <input type="submit">
</form>
</body>
</html>

templates/chats.html
{% extends "panel.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Сообщения</title>{% endblock %}
    {% include "other/links.html" %}
    {% block top-js %}{% endblock %}

</head>
<body>
    {% block cp-content %}
        <ul>
            <h3>Чаты:</h3>
            {% if user.chat_set.all|length_is:"0" %}
            <p>Чатов нету</p>
            {% else %}
            {% for element in chats %}
            <li>
                <a href="{% url 'chat' id=element.chat.pk %}">{{ element.title }}</a>
            </li>
            {% endfor %}
        {% endif %}

        </ul>
    {% endblock %}


    {% include "other/scripts.html" %}
    {% block bottom-js %}{% endblock %}

</body>
</html>

templates/header.html
<div class="blue-grey darken-2" style="">
        <div class="container">
          <div class="authBlock right " style="margin-right: 15px">
            <p style="margin: 5px">
              <a href="#">
                Войти</a>
                <span class="slash">/</span>
              <a href="#">
                Зарегистироваться
              </a>
            </p>
          </div>
        </div>
      </div>

    
      <!-- Dropdown Structure -->
      <ul id="dropdown-button-laptop-yet" class="dropdown-content">
        <li><a href="#!">О нас</a></li>
        <li><a href="#!">Правила</a></li>
        <li><a href="#!">Эксклюзив</a></li>
        <li><a href="#!">Сообщество VK</a></li>
      </ul>

      <ul id="dropdown-button-mobile-yet" class="dropdown-content">
        <li><a href="#!">О нас</a></li>
        <li><a href="#!">Правила</a></li>
        <li><a href="#!">Эксклюзив</a></li>
        <li><a href="#!">Сообщество VK</a></li>
      </ul>

      <ul id="dropdown-button-laptop-support" class="dropdown-content">
        <li><a href="#!">Написать в поддержку</a></li>
        <li><a href="#!">База знаний</a></li>
      </ul>

      <ul id="dropdown-button-mobile-support" class="dropdown-content">
        <li><a href="#!">Написать в поддержку</a></li>
        <li><a href="#!">База знаний</a></li>
      </ul>
    
      <nav style="background-color: #567F83">   
        <div class="container">
          <div class="nav-wrapper">
            <a href="#" class="brand-logo left">AtomMC</a>
            <a href="" data-activates="mobile-demo" class="button-collapse right"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
              <li><a href="">Главная</a></li>
              <li><a href="">Хостинг</a></li>
              <li><a href="">Мониторинг</a></li>
              <li><a href="">Новости</a></li>
              <li><a class="dropdown-button-laptop-support" href="#!" data-activates="dropdown-button-laptop-support">Поддержка<i class="material-icons right">arrow_drop_down</i></a></li>
              <!--<li><a href="">Новости</a></li>-->
              <li><a class="dropdown-button-laptop-yet" href="#!" data-activates="dropdown-button-laptop-yet">Ещё<i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
            <ul id="mobile-demo" class="side-nav">
              <li><a href="">Главная</a></li>
              <li><a href="">Хостинг</a></li>
              <li><a href="">Мониторинг</a></li>
              <li><a href="">Правила</a></li>
              <li><a class="dropdown-button-mobile-support" href="#!" data-activates="dropdown-button-mobile-support">Поддержка<i class="material-icons right">arrow_drop_down</i></a></li>
              <li><a class="dropdown-button-mobile-yet" href="#!" data-activates="dropdown-button-mobile-yet">Ещё<i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
          </div>
        </div>
      </nav>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
</head>
<body>
{% if user %}
    Welcome, {{ user.username }}, <a href="{% url 'panel' %}">go to panel</a> , <a href="{% url 'logout' %}">logout</a>
    {% else %}
    <a href="{% url 'login' %}?next=/">Enter</a> , <a href="{% url 'reg' %}">Reg</a>
{% endif %}
</body>
</html>

templates/links.html
{% load static %}
<!--Import Google Icon Font-->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--Import materialize.css-->
<link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
<!--Import style.css-->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/login.html
{% load static %}
<!DOCTYPE html>
  <html>
    <head>
      
      {% include "other/links.html" %}

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Вход - EvilGame</title>
    </head>
    
    <body>
      <div class="wrapper">
        <div id="header1" class="header">
          {% include "other/header.html" %}
          
          
          <div class="login-and-registration">
            <div class="container">
              <div class="row">
                <div class="col-xs-12 col-sm-8 offset-sm-2 col-md-8 offset-md-2 col-lg-8 offset-lg-2">
                  <div class="card form-card">
                    <div class="card-header lar-header">
                      <h2>Вход</h2>
                    </div>
                    <div class="card-block">
                      <form id="signin-form" action="{% url 'login' %}?next={{ next }}panel" method="POST">
                        {% csrf_token %}
                        <div class="row">
                        {% csrf_token %}
                          <div class="col-md-12">
                              {% csrf_token %}
                            <input id="inputEmail" for="inputEmail" name="inputEmail" type="text" class="form-control" placeholder="E-mail">
                            <label for="inputEmail"></label>
                          </div>
                        {% csrf_token %}
                          <div class="col-md-12 mt-input">
                              {% csrf_token %}
                            <input id="inputPassword" for="inputPassword" name="inputPassword" type="password" class="form-control" placeholder="Пароль">
                            <label for="inputPassword"></label>

                          </div>
                          {% if fail %}
                              {% csrf_token %}
                            <label style="padding-left: 15px" for="">Неправильный логин или пароль</label>
                          {% endif %}
                          
                          <div class="col-md-12 mt-input" style="padding-left: 15px;">
                            <a href="{% url 'pass_recovery' %}">Восстановить пароль</a>
                          </div>
                          
                          <!--  
                          <div class="col-md-11" style="padding: 20px 0px 20px 15px">
                            <p style="margin: 0">Регистрируясь на AtomMC, Вы автоматически принимаете <a href="#" style="color: #00A6B2">Пользовательское соглашение</a>, а так же соглашаетесь на <a href="#" style="color: #00A6B2">Обработку персональных данных</a>.</p>
                          </div>-->
                          
                        </div>
                        <div class="nav">
                          <button style="margin-top: 20px" type="submit" class="btn start-btn">Войти</button>
                          <a href = '{% url "reg" %}'" style="margin-top: 20px" class="ml-auto btn start-btn">Зарегистрироваться</a>

                        </div>
                        
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          
          
        </div>

        {% include "other/footer.html" %}
      </div>
      

      <!--Import jQuery before materialize.js-->
      {% include "other/scripts.html" %}
      <script src="{% static 'js/form-validate.js' %}" defer></script>
    </body>
  </html>

templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ text }}
    <a href="{% url 'index' %}">На главную</a>
    {% if user %}
        <a href="{% url 'panel' %}?next=/">,Мой аккаунт</a>
        {% else %}
        <a href="{% url 'login' %}?next=/">,Войти</a>
    {% endif %}
</body>
</html>

templates/messange.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ text }}
</body>
</html>

templates/password_recovery.html
{% load static %}
<!DOCTYPE html>
  <html>
    <head>
      
      {% include "other/links.html" %}

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Восстановление пароля - EvilGame</title>
    </head>
    
    <body>
    
    <div class="wrapper">
        <div id="header1" class="header">
          {% include "other/header.html" %}
          
          <div class="login-and-registration">
            <div class="container">
              <div class="row">
                <div class="col-xs-12 col-sm-8 offset-sm-2 col-md-8 offset-md-2 col-lg-8 offset-lg-2">
                  <div class="card form-card">
                    <div class="card-header lar-header">
                      <h2>Восстановление пароля</h2>
                    </div>
                    <div class="card-block">
                      <form id="signup-form"  action="{% url 'pass_recovery'  %}" method="post">
                        {% csrf_token %}
    
                        <div class="row">
                          {% csrf_token %}
                          <div class="col-md-12 mt-input">
                            {% csrf_token %}
                            <input id="inputEmail" for="inputEmail" name="inputEmail" type="text" class="form-control" placeholder="E-mail">
                            <label for=""></label>
                            {% if fail %}
                                {% csrf_token %}
                                <label for="">Такого пользователя не существует</label>
                            {% endif %}
                          </div>                          
                        </div>
                        <div class="nav">
                          <button style="margin-top: 20px" type="submit" class="btn start-btn">Восстановить</button>
                          <a href="{% url "reg" %}" style="margin-top: 20px" class="ml-auto btn start-btn">Регистрация</a>
                          <a href="{% url "login" %}?next=/" style="margin-top: 20px; margin-left: 10px" class="btn start-btn">Войти</a>
                        </div>
                        
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          
          
        </div>

        {% include "other/footer.html" %}
      </div>
      

      <!--Import jQuery before materialize.js-->
      {% include "other/scripts.html" %}
      <script src="{% static 'js/form-validate.js' %}" defer></script>
    </body>
  </html>

templates/password_recovery1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'pass_recovery'  %}" method="post">
    {% csrf_token %}
    {% if fail %}
        Такого пользователя не существует
    {% endif %}
    <input title="Логин или пароль" name="value">
    <input type="submit">
</form>
</body>
</html>

templates/reg.html
{% load static %}
<!DOCTYPE html>
  <html>
    <head>
      
      {% include "other/links.html" %}

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Регистрация - EvilGame</title>
    </head>
    
    <body>
    
    <div class="wrapper">
        <div id="header1" class="header">
          {% include "other/header.html" %}
          
          <div class="login-and-registration">
            <div class="container">
              <div class="row">
                <div class="col-xs-12 col-sm-8 offset-sm-2 col-md-8 offset-md-2 col-lg-8 offset-lg-2">
                  <div class="card form-card">
                    <div class="card-header lar-header">
                      <h2>Регистрация</h2>
                    </div>
                    <div class="card-block">
                      <form id="signup-form"  action="{% url 'reg' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                          <div class="col-md-6">
                            <input id="inputFirstName" for="inputFirstName" name="inputFirstName" type="text" class="form-control" placeholder="Имя">
                            <label for="inputFirstName"></label>
                            
                          </div>
                          <div class="col-md-6">
                            <input id="inputLastName" for="inputLastName" name="inputLastName" type="text" class="form-control" placeholder="Фамилия">
                            <label for="inputLastName"></label>
                          </div>
                          <div class="col-md-12 mt-input">
                            <input id="inputEmail" for="inputEmail" name="inputEmail" type="text" class="form-control" placeholder="E-mail">
                            <label for="inputEmail"></label>
                            {% if not inputEmail %}
                            <br>
                                <label for="">Пользователь с таким E-mail уже существует</label>

                            {% endif %}
                          </div>
                          <div class="col-md-12 mt-input">
                            <input id="inputPassword" for="inputPassword" name="inputPassword" type="password" class="form-control" placeholder="Пароль">
                            <label for="inputPassword"></label>
                          </div>
                          
                          <div class="col-md-11" style="padding: 20px 0px 20px 15px">
                            <p style="margin: 0">Регистрируясь на EvilGame, Вы автоматически принимаете <a href="#" style="color: #00A6B2">Пользовательское соглашение</a>, а так же соглашаетесь на <a href="#" style="color: #00A6B2">Обработку персональных данных</a>.</p>
                          </div>
                          
                        </div>
                        <div class="nav">
                          <button style="margin-top: 20px" type="submit" class="btn start-btn">Зарегистрироваться</button>
                          <a href="{% url "login" %}?next=/" style="margin-top: 20px" class="ml-auto btn start-btn">Войти</a>
                        </div>
                        
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          
          
        </div>

        {% include "other/footer.html" %}
      </div>
      

      <!--Import jQuery before materialize.js-->
      {% include "other/scripts.html" %}
      <script src="{% static 'js/form-validate.js' %}" defer></script>
    </body>
  </html>

templates/servers_for_sale.html
{% extends "panel.html" %}
{% load static %}
{% block panel-title %}Купить сервер{% endblock %}

{% block panel-header%}
<h3>Купить сервер</h3>
{% endblock %}

{% block panel-body %}
<div class="row">
    
    {% for server in servers %}
    <li>
    <ul>
        <li><a href="{% url "buy_server" server.id %}" >{{ server.name }}</a></li>
    <li>{{ server.price }}</li>
    </ul>

    </li>
{% endfor %}
</div>
{% endblock %}

templates/signin.html
<!DOCTYPE html>
  <html>
    <head>
      
      {% include "other/links.html" %}

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    
    <body>
    
    {% include "other/header.html" %}

    <div class="call-to-action">
      main class="valign-wrapper call-to-action">
        <div class="container">
          <div class="row">
            <div class="col s12 m8 l8 xl6 offset-m2 offset-l2 offset-xl3">
              <div class="test-container z-depth-3" style="padding: 0px;">  
                <div class="red darken-1"> 
                  <div class="container center-align">
                    <h3 style="margin: 0px; padding: 20px; color: #EFEBE9;">Вход</h3>
                  </div>
                </div>
                <div class="brown lighten-5" style="padding: 20px; z-index: 2"> 
                  <div class="container"> 
                    <div class="row">
                      <form id="signin-form" role="form" class="col s12 form">
                        <div class="row">
                          <div class="input-field col s12 m12 l12 xl12 left-align">
                            <input id="inputEmail" type="text" class="validate" for="inputEmail" name="inputEmail">
                            <label for="inputEmail">E-mail</label>
                          </div>
                          <div class="input-field col s12 m12 l12 xl12 left-align">
                            <input id="inputPassword" type="password" class="validate" for="inputPassword" name="inputPassword">
                            <label for="inputPassword">Пароль</label>
                          </div>
                          <div class="left-align">
                            <p><a href="" style="position: relative; color: #E53935; left: .75rem;">Восстановить пароль</a></p>
                          </div>
                          <div class="col s12 center-align" style="margin-top: 20px">
                            <button class="btn waves-effect waves-light red darken-1" type="submit" name="action">Войти
                              <i class="material-icons right">send</i>
                            </button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      {% include "other/footer.html" %}

    </div>
      

      <!--Import jQuery before materialize.js-->
      {% include "other/scripts.html" %}
      <script src="js/navigation.js"></script><!--Этот скрипт очень важен, с помощью него работает навигация!!!-->
      <script src="js/form-validate.js" defer></script>
    </body>
  </html>